package com.hakim.hakimtools.text;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author Hakim
 */
public class CommaSeparator extends javax.swing.JFrame {

    /**
     * Creates new form CommaSeparator
     */
    public CommaSeparator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lineArea = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        commaArea = new javax.swing.JTextPane();
        lineToCommaBtn = new javax.swing.JButton();
        commaToLine = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comma Separator");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lineArea.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        lineArea.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lineAreaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(lineArea);

        commaArea.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(commaArea);

        lineToCommaBtn.setFont(new java.awt.Font("Fira Code Medium", 0, 18)); // NOI18N
        lineToCommaBtn.setText(">");
        lineToCommaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineToCommaBtnActionPerformed(evt);
            }
        });

        commaToLine.setFont(new java.awt.Font("Fira Code Medium", 0, 18)); // NOI18N
        commaToLine.setText("<");
        commaToLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaToLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commaToLine)
                    .addComponent(lineToCommaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(lineToCommaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commaToLine)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lineToCommaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineToCommaBtnActionPerformed

        String lineString = lineArea.getText();
        String[] lines = lineString.split("\\n");

        StringBuilder sb = new StringBuilder();
        for (String line : lines) {

            String item = line.trim().replace("\\n", "");
            sb.append(item).append(",");
        }

        commaArea.setText(sb.toString());
    }//GEN-LAST:event_lineToCommaBtnActionPerformed

    private void lineAreaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lineAreaAncestorAdded
        // Todo : no use
    }//GEN-LAST:event_lineAreaAncestorAdded

    private void commaToLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaToLineActionPerformed

        String commaText = commaArea.getText();
        String[] itemList = commaText.split("\\,");

        String result = String.join("\n", itemList);
        
        lineArea.setText(result);
    }//GEN-LAST:event_commaToLineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommaSeparator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommaSeparator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane commaArea;
    private javax.swing.JButton commaToLine;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane lineArea;
    private javax.swing.JButton lineToCommaBtn;
    // End of variables declaration//GEN-END:variables
}
