package com.hakim.hakimtools.text;

import com.formdev.flatlaf.FlatLightLaf;
import com.hakim.hakimtools.util.ComparerTask;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Hakim
 */
public class Separator extends javax.swing.JFrame {

    /**
     * Creates new form Separator
     */
    public Separator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultText = new javax.swing.JTextPane();
        clearBtn = new javax.swing.JButton();
        itemCounter = new javax.swing.JLabel();
        chooser = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        text1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        text2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unique Item Seperator");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        button.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        button.setForeground(new java.awt.Color(153, 0, 153));
        button.setText("Procced");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        resultText.setEditable(false);
        resultText.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(resultText);

        clearBtn.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(255, 0, 102));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        itemCounter.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        chooser.setFont(new java.awt.Font("Fira Code Medium", 0, 12)); // NOI18N
        chooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "From Left", "From Right", "Both", " " }));

        text1.setFont(new java.awt.Font("Fira Code", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(text1);

        jScrollPane4.setViewportView(jScrollPane1);

        text2.setFont(new java.awt.Font("Fira Code", 0, 10)); // NOI18N
        jScrollPane2.setViewportView(text2);

        jScrollPane5.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(itemCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clearBtn)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button)
                    .addComponent(clearBtn)
                    .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemCounter, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        ExecutorService service = Executors.newFixedThreadPool(10);
        List<String> unique = new ArrayList<>();

        String field1Text = text1.getText();
        String field2Text = text2.getText();
        
        int selectedIndex = chooser.getSelectedIndex();
        
        switch (selectedIndex) {
            case 0 -> {
                separateFromLeft(field2Text, service, field1Text, unique);
            }
            case 1 -> {
                separateFromRight(field2Text, service, field1Text, unique);
            }
            default -> {
                separateFromRight(field2Text, service, field1Text, unique);
                separateFromLeft(field2Text, service, field1Text, unique);
            }
        }

        System.out.println(unique);

        // Generate result 
        StringBuilder builder = new StringBuilder();
        for (String result : unique) {
            builder.append(result);

            if (unique.indexOf(result) != unique.size() - 1) {
                builder.append(",");
            }
        }

        resultText.setText(builder.toString());
        itemCounter.setText("Found " + unique.size() + " items");

        service.shutdown();
    }//GEN-LAST:event_buttonActionPerformed

    private void separateFromLeft(String field2Text, ExecutorService service, String field1Text, List<String> unique) {
        for (String nameItem : field2Text.split(",")) {

            ComparerTask task = new ComparerTask(nameItem.trim(), convertToList(field1Text.split(",")));
            Future<Boolean> contains = service.submit(task);

            try {
                if (!contains.get()) {
                    unique.add(nameItem.trim());
                }
            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(Separator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void separateFromRight(String field2Text, ExecutorService service, String field1Text, List<String> unique) {
        for (String nameItem : field1Text.split(",")) {

            ComparerTask task = new ComparerTask(nameItem.trim(), convertToList(field2Text.split(",")));
            Future<Boolean> contains = service.submit(task);

            try {
                if (!contains.get()) {
                    unique.add(nameItem.trim());
                }
            } catch (InterruptedException | ExecutionException ex) {
                Logger.getLogger(Separator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:

        resultText.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private List<String> convertToList(String[] arr) {
        List<String> list = new ArrayList<>();

        for (String item : arr) {
            list.add(item.trim());
        }

        return list;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Separator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Separator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JComboBox<String> chooser;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel itemCounter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextPane resultText;
    private javax.swing.JTextPane text1;
    private javax.swing.JTextPane text2;
    // End of variables declaration//GEN-END:variables
}
