package com.hakim.hakimtools.datetime;

import com.formdev.flatlaf.FlatLightLaf;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import java.util.Set;
import javax.swing.UIManager;

/**
 *
 * @author Hakim
 */
public class ZoneTime extends javax.swing.JFrame {

    private final DateTimeFormatter formatter = DateTimeFormatter.ofLocalizedDateTime(FormatStyle.LONG);

    /**
     * Creates new form ZoneTime
     */
    public ZoneTime() {
        initComponents();
        initZones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chooser = new javax.swing.JComboBox<>();
        finderBtn = new javax.swing.JButton();
        result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        chooser.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        chooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        finderBtn.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        finderBtn.setText("Find");
        finderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finderBtnActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finderBtn)
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finderBtn))
                .addGap(47, 47, 47)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finderBtnActionPerformed

        String selectedItem = chooser.getSelectedItem().toString();
        renderDateTime(selectedItem);
    }//GEN-LAST:event_finderBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {

            UIManager.setLookAndFeel(new FlatLightLaf());

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZoneTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZoneTime().setVisible(true);
            }
        });
    }

    private void initZones() {

        Set<String> availableZoneIds = ZoneId.getAvailableZoneIds();
        List<String> zones = availableZoneIds.stream().sorted().toList();
        for (String zone : zones) {
            chooser.addItem(zone);
        }

        // Set default zone and time
        ZoneId systemDefault = ZoneId.systemDefault();
        chooser.setSelectedItem(systemDefault.toString());

        renderDateTime(systemDefault.toString());
    }

    private void renderDateTime(String zone) {

        ZonedDateTime zonedDateTime = ZonedDateTime.now(ZoneId.of(zone));
        result.setText(formatter.format(zonedDateTime));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chooser;
    private javax.swing.JButton finderBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
